### ISSUE TITLE
Couldnt scan a file

### ISSUE THREAD

**Issue by Leclowndu93150** [MCRcortex/nekodetector#3]
java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:262)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
        at me.cortex.jarscanner.Detector.scanClass(Detector.java:77)
        at me.cortex.jarscanner.Detector.lambda$scan$1(Detector.java:26)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.base/java.util.zip.ZipFile$EntrySpliterator.tryAdvance(Unknown Source)
        at java.base/java.util.Spliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
        at me.cortex.jarscanner.Detector.scan(Detector.java:31)
        at me.cortex.jarscanner.Main$1.lambda$visitFile$0(Main.java:51)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Failed to scan: C:\Users\karim\AppData\Roaming\PrismLauncher\instances\AMP - Awakening Reforged\minecraft\mods\Damage-Indicators-Mod-1.7.10.jar

**Comment by hjake123** [comment]
Here's another instance of the same error with the most recent snapshot build (jarscanner-1.0-SNAPSHOT from build #8):

`java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:262)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
        at me.cortex.jarscanner.Detector.scanClass(Detector.java:79)
        at me.cortex.jarscanner.Detector.lambda$scan$1(Detector.java:19)
        at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.zip.ZipFile$EntrySpliterator.tryAdvance(ZipFile.java:558)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
        at me.cortex.jarscanner.Detector.scan(Detector.java:17)
        at me.cortex.jarscanner.Main$1.lambda$visitFile$0(Main.java:57)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Failed to scan: D:\PrismMC\instances\Vault Hunters 3rd Edition\minecraft\mods\Terralith_v2.2.3.jar`

This file was downloaded in like January so there's little chance it's infected, in case that matters.

This error did not prevent the scan from completing, though I haven't tried intentionally placing an infected file in the scanned directory, and there was no detection, so I suppose a false negative is possible.

**Comment by Leclowndu93150** [comment]
Failed to scan: C:\Users\karim\AppData\Local\.ftba\instances\00d6dbaf-c71b-4360-ac0b-4227a795c4dc\mods\Terralith_v2.2.1a.jar
java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:262)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
        at me.cortex.jarscanner.Detector.scanClass(Detector.java:94)
        at me.cortex.jarscanner.Detector.lambda$scan$1(Detector.java:25)
        at java.base/java.util.stream.MatchOps$1MatchSink.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.base/java.util.zip.ZipFile$EntrySpliterator.tryAdvance(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.anyMatch(Unknown Source)
        at me.cortex.jarscanner.Detector.scan(Detector.java:23)
        at me.cortex.jarscanner.Main$1.lambda$visitFile$0(Main.java:65)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Failed to scan: C:\Users\karim\AppData\Roaming\PrismLauncher\instances\AMP - Awakening Reforged\minecraft\mods\Damage-Indicators-Mod-1.7.10.jar
same shit

**Comment by Leclowndu93150** [comment]
looks like it is still running

**Comment by Huskydog9988** [comment]
Note to self: this error seems to somehow be coming from the `ClassReader` in `Decoder#scanClass`. Not sure why, but maybe due to the reader being unable to parse the provided jars.

**Comment by Leclowndu93150** [comment]
ah
