### ISSUE TITLE
Error: Failed to scan jar file

### ISSUE THREAD

**Issue by BinaryVigilante** [MCRcortex/nekodetector#52]
I'm getting this error while scanning my home directory on Arch Linux:
```
Failed to scan Jar file: /home/binary/mnt/games/badlion/.minecraft/versions/BLClient/PRODUCTION3/1.19.4/BLClient.jar
Error:9
```
I'm running Nekodetector as root.

**Comment by comicsansgreenki** [comment]
This happened for me with Betacraft's `discord_rpc.jar` plugin.
Console log:
```
java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:228)
	at java.util.zip.ZipFile.<init>(ZipFile.java:157)
	at java.util.jar.JarFile.<init>(JarFile.java:171)
	at java.util.jar.JarFile.<init>(JarFile.java:135)
	at me.cortex.jarscanner.Main$1.lambda$visitFile$0(Main.java:181)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
